### ISSUE TITLE
A101_Explore-phenotype-tables_Python.ipynb  - Not Working

### ISSUE THREAD

**Issue by 42elenz** [UK-Biobank/UKB-RAP-Notebooks-Access#13]
Dear Team, 
Thank you for the notebooks. Unfortunately the provided Jupyter Notebook.

This line does not work:
`participant_data = participant.retrieve_fields(engine=dxdata.connect(dialect="hive+pyspark"), coding_values="replace", limit=100)`

I get this Error:
**ValueError: retrieve_fields is only supported using a spark connection.Thrift connection is not supported. Check your engine connection setting or environment.**

**Comment by DaisyVinter** [comment]
Hi, thanks for using the notebooks! Can you check you are using a JupyterLab instance with Spark Cluster 
![image](https://github.com/user-attachments/assets/77c4a7e5-c4ca-4ad7-b8ac-710f8786d806) instead of Single Node? This is required to retrieve fields from the dataset.
