### ISSUE TITLE
URL to Jupyter Notebook does not open

### ISSUE THREAD

**Issue by LuRoe7** [UK-Biobank/UKB-RAP-Notebooks-Access#16]
I want to intitialze a Jupyter Notebook on the UKBB RAP. I´m following the steps described in this video as part of the UKBB tutorial https://www.youtube.com/watch?v=butgJQf_mhI&list=PLRkZ0Fz-n3Z71Pt9h8-0AEweopm0SVlTr&index=8. But when I click on the Worker URL on the project-specific Monitor tab, the Jupyter Notebook does not open and I get a page not found error. This happens with Google Chrome on a Windows computer and with Firefox on Ubuntu (different laptop). Any ideas how to troubleshoot this issue?

**Comment by oliver-gray** [comment]
This issue board is available for issues pertaining specifically to the notebooks and tools provided.
More general issues should be posted to the UK Biobank Community.
Issues that are specific to your project should be emailed to access@ukbiobank.ac.uk.

Please also see the DNAnexus RAP GitBook for guidance on using the RAP. The following troubleshooting area may be of assistance to you:
https://dnanexus.gitbook.io/uk-biobank-rap/working-on-the-research-analysis-platform/running-analysis-jobs/jupyterlab#troubleshooting
